# Hijack all DNS queries to portal IP when AP is active
address=/#/10.42.1.1
# Ensure captive probe domains also resolve to us
address=/captive.apple.com/10.42.1.1
address=/connectivitycheck.gstatic.com/10.42.1.1
address=/connectivitycheck.android.com/10.42.1.1
address=/www.google.com/10.42.1.1
address=/clients3.google.com/10.42.1.1
address=/msftconnecttest.com/10.42.1.1
address=/www.msftncsi.com/10.42.1.1
